version: "2"
services:
  antidote1:
    image: mweber/antidotedb:latest # Specify the image to start the container from. Can either be a repository/tag or a partial image ID
    ports:
     - "127.0.0.1:8087:8087"
    environment: # Add environment variables. You can use either an array or a dictionary.
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
  antidote2:
    image: mweber/antidotedb:latest
    ports:
     - "127.0.0.1:8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"

  link:
    image: erlang:19
    volumes: #Mount host folders or named volumes. Named volumes need to be specified with the top-level volumes key.
      - .:/code
    command: '/code/link.sh'
    links: # Link to containers in another service. Either specify both the service name and a link alias ("SERVICE:ALIAS"), or just the service name.
      - antidote1
      - antidote2

  #docker-compose exec antidote1 tc qdisc replace dev eth0 root netem loss 100%
  #docker-compose exec antidote1 tc qdisc replace dev eth0 root netem loss 0%

